class DataTypes:
    OBJECT = 'object'
    INTEGER = 'int64'
    INT64 = 'int64'
    INT32 = 'int32'
    INT16 = 'int16'
    INT8 = 'int8'
    FLOAT = 'float64'
    FLOAT64 = 'float64'
    FLOAT32 = 'float32'
    DATETIME64 = 'datetime64[ns]'
    TIMEDELTA64 = 'timedelta64[ns]'
    BOOLEAN = 'bool'
    CATEGORY = 'category'
    COMPLEX = 'complex'